language: ruby
rvm:
 - 2.3.3
services:
 - mysql
 - neo4j
#before_install:
before_script:
 # mysql: db setup and db config move
 - cp config/database.travis.yml config/database.yml
 - bundle exec rake db:create db:structure:load
 # neo4j: copy
 - cp config/neo4j.travis.yml config/neo4j.yml