env:
  global:
    - CC_TEST_REPORTER_ID=$TEST_REPORTER_ID
language: node_js
node_js:
 - stable
install:
 - npm install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build --debug
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
cache:
  directories:
    - node_modules
after_success:
# - npm run coverage
# - npm run docs
deploy:
 - provider: npm
   skip_cleanup: true
   email: "contact@popotojs.com"
   api_key: $NPM_TOKEN
notifications:
 slack: pipot:9bOymKdaSOJyFzqBStPiLo6l
 on_success: always
